/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Speed:": "速度:",
    "Speed Game": "速度游戏",
    "Stop Meditation": "停止冥想",
    "So what do I do here?": "那我在这里做什么？",
    "Save Management": "存档管理",
    "Save Settings": "保存设置",
    "Robotics Section": "机器人学章节",
    "Restart Entire Game": "重新开始整个游戏",
    "Quadruple Ascension": "四次转生",
    "Crit:": "暴击:",
    "Crit Dmg:": "暴击伤害:",
    "Cure for Delusion": "解痴之术",
    "Export Save": "导出存档",
    "Exit": "退出",
    "Eternal Ascension": "永恒转生",
    "Exporting your game will save a file to your Downloads folder. (Currently does not work on mobile)": "导出你的游戏将保存一个文件到你的下载文件夹。(目前不能在手机上使用)",
    "From:": "从:",
    "To:": "到:",
    "Foreshadowing": "伏笔",
    "GameStop": "游戏驿站",
    "Gameplay Options": "游戏选项",
    "HALL OF POWER": "力量殿堂",
    "Hopium": "希望主义",
    "I Can't Math": "我不会数学",
    "Import Save": "导入存档",
    "Infinite Embrace": "无限拥抱",
    "Knowledge per second:": "每秒的知识:",
    "Knowledge Generation": "知识生成",
    "Knowledge is Power": "知识就是力量",
    "Less Diminishing God-Mode": "递减较少的上帝模式",
    "Knowledgeable Cookie": "知识渊博的饼干",
    "Give Feedback": "提供反馈",
    "HALL OF LOVE": "爱情殿堂",
    "Hall of Love": "爱情殿堂",
    "Hall of Knowledge": "知识殿堂",
    "History Section": "历史章节",
    "Close": "关闭",
    "Confirm": "确认",
    "Health:": "生命值:",
    "Gravity:": "重力:",
    "Focus:": "专注:",
    "Forfeit": "没收",
    "2D Ascension": "2D转生",
    "Trade": "交易",
    "Amount:": "数量:",
    "Damage:": "伤害:",
    "elusion:": "逃避:",
    "erenity:": "灵敏:",
    "Defense:": "防御:",
    "Dodge:": "闪避:",
    "Achievement Hypercharge": "成就超级充能",
    "Arena Size:": "竞技场大小：",
    "Big Crunch": "大收缩",
    "Buy Max": "购买最大",
    "Cancel": "取消",
    "Celestial Collector": "天体收集器",
    "Collect Copium": "收集精神",
    "Collect Yacht Money": "收集游艇钱",
    "Cookie Clicker Clicker": "无尽的饼干点击器",
    "Cookie Boost": "饼干提升",
    "Copium": "精神",
    "Crunch Knowledge": "收缩知识",
    "Donate": "捐赠",
    "Game Trailer": "游戏预告片",
    "Gravity Well": "重力井",
    "Hall of Balance": "平衡之殿",
    "Hall of Power": "力量之殿",
    "Hall of Power Auto-Buy": "力量之殿自动购买",
    "Load File": "加载文件",
    "Math Game": "数学游戏",
    "Master of Time": "时间的主宰",
    "Prestige Base": "声望基数",
    "Prestige": "声望",
    "Automation Settings": "自动化设置",
    "Automation": "自动化",
    "Basic Resource Boost": "基础资源提升",
    "Buy Seen": "购买可见",
    "Celestial Precision": "天体精度",
    "Click Speed Demon": "点击速度恶魔",
    "Collect Delusion": "收集妄想",
    "Collect Troll Points": "收集巨魔点数",
    "Community & Support": "社区 & 支持",
    "Compressed Power": "压缩之力",
    "Condensed Power": "凝聚之力",
    "Confirm Selection": "确认选择",
    "Copy Save": "复制存档",
    "Copium per second:": "精神每秒:",
    "Copium Surge": "精神狂热",
    "Cosmic Dynamics Section": "宇宙动力学组",
    "Cosmic Embrace": "宇宙拥抱",
    "Cosmic Gamekeeper": "宇宙猎场守护者",
    "Buy Markers": "购买标记",
    "Ball Size:": "球大小:",
    "Buy me a Coffee": "请作者喝杯咖啡",
    "Cookie Recipe": "饼干配方",
    "Decisions, decisions...": "决定，决定...",
    "You have many Automation features yet to be unlocked.": "您有许多自动化功能尚未解锁。",
    "You made it": "你做到了",
    "Welcome to the start of your epic journey. Whether you’re here for the memes, the deep existential pondering, or just to click things—cheers to you! 🍷": "欢迎来到你史诗般的旅程的开始。无论你是来这里看表情包的，还是来进行深刻的存在主义思考的，或者只是来点东西的——祝你快乐！🍷",
    "Max HP:": "最大生命值:",
    "Map to Hall of Power": "前往力量之殿的地图",
    "Master of Bargains": "讨价还价大师",
    "Master of Elements": "元素大师",
    "Mixed": "混合",
    "But don’t get too comfortable! Ahead lie challenges that will test your wit, patience, and strategic thinking. There will be walls to break through, and the path forward isn’t always a straight line. But hey, if Leo can win an Oscar, you can solve a few strategic puzzles, right?": "但是不要太舒服了！前方的挑战将考验你的智慧、耐心和战略思维。总会有障碍需要突破，前进的道路并不总是一条直线。但是，如果里奥能赢得奥斯卡奖，你就能解决一些战略难题，对吧？",
    "Let the games begin—click, explore, and outsmart every obstacle in your way!": "让游戏开始吧——点击、探索、智胜路上的每一个障碍！",
    "Restart This Prestige": "重新开始这个声望",
    "Purchased Upgrades": "已购买升级",
    "Clickable": "可点击",
    "Luck Game": "幸运游戏",
    "Memory Game": "记忆游戏",
    "Luck is Rigged": "运气被操纵了",
    "Mini Gamer": "迷你玩家",
    "Min-Maxing Love": "最小最大的爱",
    "Music": "音乐",
    "Rise Stronger!": "变得更强！",
    "Congratulations! You have unlocked the first of many prestige layers. This one is straightforward, but it represents something much greater: the beginning of a journey filled with deeper challenges and complexity.": "恭喜你!你已经解锁了许多声望层中的第一个。这一个很简单，但它代表了更大的意义：一个充满更深层次挑战和复杂性的旅程的开始。",
    "Prestige isn’t just a reset—it’s a testament to your resilience, symbolizing the strength to rise again, stronger and wiser. While this first step may seem simple, future layers will add layers of strategy and depth that will truly test your skills.": "声望不仅仅是一种重置——它是你韧性的证明，象征着再次崛起的力量，更强大、更聪明。虽然这第一步看起来很简单，但以后的关卡会增加策略和深度，真正考验你的技能。",
    "By choosing Prestige, you’re not just starting over; you’re gaining a powerful multiplier that will enhance everything you do. Each click, each resource, and every upgrade will be boosted, setting the stage for even greater achievements.": "通过选择声望，你不仅仅是重新开始；你正在获得一个强大的乘数，将提高你所做的一切。每次点击，每次资源和每次升级都会得到提升，为更大的成就奠定基础。",
    "Are you ready to embrace this opportunity? To rebuild with newfound strength and surpass your past progress? Prestige now, and begin your ascent to greatness once more!": "你准备好迎接这个机会了吗？用新发现的力量重建并超越你过去的进步？现在就开始声望，并开始你再次走向伟大！",
    "Skill": "技能",
    "Support the Game": "支持游戏",
    "Time:": "时间:",
    "Stun:": "眩晕:",
    "Study Accelerator": "学习加速器",
    "Tears of Joy": "喜极而泣",
    "Temporal Drag": "时间阻力",
    "Temporal Flux": "时间通量",
    "Temporal Guard": "时间守卫",
    "Tenfold Ascension": "十倍转生",
    "Infinite Prestige": "无限声望",
    "Infinite Collapse": "无限坍缩",
    "Mystic Rebound": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Stellar Harvest": "恒星收获",
    "Stellar Cookie": "恒星饼干",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Copium: ": "Copium: ",
    "Delusion: ": "妄想: ",
    "TrollPoints: ": "巨魔点数: ",
    "YachtMoney: ": "游艇钱数: ",
    "Achievement Boost": "成就提升",
    "Love Points": "爱心点数",
    "Prestige: ": "声望: ",
    "Cosmic Truth ": "宇宙真理 ",
    "Degens Idle v": "Degens放置 v",
    "Serene Boost": "宁静提升",
    "Oversurged Power": "",
    "Number Format: ": "数值格式: ",
    "Prestige Unlocked: ": "声望解锁: ",
    "Knowledge Infusion": "知识灌输",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^PRESTIGE \(x(.+) MULT\)$/, '声望 (x$1 乘数)'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) times$/, '$1 次'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)x Copium gain.$/, '$1x 精神 增益.'],
    [/^([\d\.,]+)x Delusion gain.$/, '$1x 妄想 增益.'],
    [/^([\d\.,]+)x Troll Points gain.$/, '$1x 巨魔点数 增益.'],
    [/^([\d\.,]+)x Yacht Money gain.$/, '$1x 游艇钱 增益.'],
    [/^Trade ([\d\.,]+)\%$/, '交易 $1\%'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) Knowledge$/, '成本：$1 知识'],
    [/^Cost: (.+) Power$/, '成本：$1 力量'],
    [/^Cost: (.+) Love Points$/, '成本：$1 爱心点数'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);